config/routes.rb
Rails.application.routes.draw do
  resources :authors
  devise_for :users

  resources :books do
    resources :loans
  end
  
  root 'books#index'
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    
    if user.admin?
      can :manage, :all   
    else
      can :read, :all
    end
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
  validates :name, presence: true
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :author
	has_many :loan
	validates :title, :author_id, presence: true
end

app/models/loan.rb
class Loan < ActiveRecord::Base
	belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  def admin?
    self.role == "admin"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        if request['author']['from_books'] == "true"
          format.html { redirect_to new_book_path}
        else
          format.html { redirect_to @author, notice: 'Author was successfully created.' }
          format.json { render :show, status: :created, location: @author }
        end
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :art_name, :dob)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all.includes :author
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    @authors = Author.order(:name)
  end

  # GET /books/1/edit
  def edit
    @authors = Author.order(:name)
  end

  # POST /books
  # POST /books.json
  def create
    @authors = Author.order(:name)
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author_id, :isbn, :language, :translator, :cover, :edition, :year)
    end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:book_id, :date, :loan, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/authors/_authors_list.html.slim
table
  thead
    tr
      th Name
      th Art name
      th Dob
      th
      th
      th

  tbody
    - Author.all.each do |author|
      tr
        td = author.name
        td = author.art_name
        td = author.dob
        td = link_to 'Show', author
        td = link_to 'Edit', edit_author_path(author)
        td = link_to 'Destroy', author, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/authors/_form.html.slim
= form_for @author do |f|
  - if @author.errors.any?
    #error_explanation
      h2 = "#{pluralize(@author.errors.count, "error")} prohibited this author from being saved:"
      ul
        - @author.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :art_name
    = f.text_field :art_name
  .field
    = f.label :dob
    = f.text_field :dob
    = f.hidden_field :from_books, value: request['format'] == "from_books"
  .actions = f.submit 'Save'

app/views/authors/_list.html.slim
table
  thead
    tr
      th Name
      th Art name
      th Dob
      th
      th
      th

  tbody
    - Author.all.each do |author|
      tr
        td = author.name
        td = author.art_name
        td = author.dob
        td = link_to 'Show', author
        td = link_to 'Edit', edit_author_path(author)
        td = link_to 'Destroy', author, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/authors/edit.html.slim
h1 Editing author

== render 'form'

= link_to 'Show', @author
'|
= link_to 'Back', authors_path

app/views/authors/index.html.slim
h1 Listing authors
== render 'authors_list'

  = link_to 'New Author', new_author_path

app/views/authors/new.html.slim
h1 New author

== render 'form'

= link_to 'Back', :back

app/views/authors/show.html.slim
p#notice = notice

p
  strong Name:
  = @author.name
p
  strong Art name:
  = @author.art_name
p
  strong Dob:
  = @author.dob

= link_to 'Edit', edit_author_path(@author)
'|
= link_to 'Back', authors_path

app/views/books/_admin_books_list.html.slim
table
  thead
    tr
      th Title
      th Author
      th Isbn
      th Language
      th Translator
      th Cover
      th Edition
      th Year
      th
      th
      th

  tbody
    - @books.each do |book|
      tr
        td = book.title
        - unless book.author.nil?
          td = book.author.art_name
        td = book.isbn
        td = book.language
        td = book.translator
        td = book.cover
        td = book.edition
        td = book.year
        td = link_to 'Show', book, class: "button", id: "book-show-button"
        td = link_to 'Edit', edit_book_path(book)
        td = link_to 'Destroy', book, method: :delete, data: {:confirm => 'Are you sure?'}

app/views/books/_admin_list.html.slim
table
  thead
    tr
      th Title
      th Author
      th Isbn
      th Language
      th Translator
      th Cover
      th Edition
      th Year
      th
      th
      th

  tbody
    - @books.each do |book|
      tr
        td = book.title
        - unless book.author.nil?
          td = book.author.art_name
        td = book.isbn
        td = book.language
        td = book.translator
        td = book.cover
        td = book.edition
        td = book.year
        td = link_to 'Show', book, class: "button", id: "book-show-button"
        td = link_to 'Edit', edit_book_path(book)
        td = link_to 'Destroy', book, method: :delete, data: {:confirm => 'Are you sure?'}

app/views/books/_form.html.slim
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      h2 = "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      ul
        - @book.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :author
    = f.collection_select :author_id, @authors, :id, :name, include_blank: true
    = link_to "New author?", new_author_path(:from_books), method: :get
  .field
    = f.label :isbn
    = f.text_field :isbn
  .field
    = f.label :language
    = f.text_field :language
  .field
    = f.label :translator
    = f.text_field :translator
  .field
    = f.label :cover
    = f.text_field :cover
  .field
    = f.label :edition
    = f.text_field :edition
  .field
    = f.label :year
    = f.number_field :year
  .actions = f.submit 'Save'

app/views/books/_list.html.slim
table
  thead
    tr
      th Title
      th Author
      th Isbn
      th Language
      th Translator
      th Cover
      th Edition
      th Year
      th
      th
      th

  tbody
    - @books.each do |book|
      tr
        td = book.title
        - unless book.author.nil?
          td = book.author.art_name
        td = book.isbn
        td = book.language
        td = book.translator
        td = book.cover
        td = book.edition
        td = book.year
        td = link_to 'Show', book, class: "button", id: "book-show-button"
        td = link_to 'Edit', edit_book_path(book)
        td = link_to 'Destroy', book, method: :delete, data: {:confirm => 'Are you sure?'}

app/views/books/_user_books_list.html.slim
table
  thead
    tr
      th Title
      th Author
      th Isbn
      th Language
      th Translator
      th Cover
      th Edition
      th Year
      th

  tbody
    - @books.each do |book|
      tr
        td = book.title
        - unless book.author.nil?
          td = book.author.art_name
        td = book.isbn
        td = book.language
        td = book.translator
        td = book.cover
        td = book.edition
        td = book.year
        td = link_to 'Loan', new_book_loan_path(book)

app/views/books/edit.html.slim
h1 Editing book

== render 'form'

= link_to 'Show', @book
'|
= link_to 'Back', books_path

app/views/books/index.html.slim
- if user_signed_in?
  -if current_user.admin?
    - unless @books.empty?
    == render 'books/admin_books_list'
    br
    == render 'authors/authors_list'
    br
    == render 'loans/loan_list'
    br
    h3 Opções
    = link_to "New author", new_author_path, method: :get
    br
    = link_to "New book", new_book_path, method: :get
    br
    = link_to "Sign Out", destroy_user_session_path, method: :delete
  -else
    - unless @books.empty?
    == render 'books/user_books_list'
    br
    = link_to "Sign Out", destroy_user_session_path, method: :delete
- else
  h1 Início
  = link_to "Sign In", new_user_session_path, method: :get
  br
  = link_to "Sign up", new_user_registration_path, method: :get
  br
  == render 'books/user_books_list'

app/views/books/new.html.slim
h1 New book

== render 'form'

= link_to 'Back', books_path

app/views/books/show.html.slim
p#notice = notice

p
  strong Title:
  = @book.title
p
  strong Author:
  - unless @book.author.nil?
      = @book.author.art_name
p
  strong Isbn:
  = @book.isbn
p
  strong Language:
  = @book.language
p
  strong Translator:
  = @book.translator
p
  strong Cover:
  = @book.cover
p
  strong Edition:
  = @book.edition
p
  strong Year:
  = @book.year

= link_to 'Edit', edit_book_path(@book)
'|
= link_to 'Back', books_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Librarian
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = yield
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/layouts/applications.html.slim
doctype html
html
  head
    title Librarian
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = yield
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/loans/_form.html.slim
= form_for :loan do |f|
  - if @loan.errors.any?
    #error_explanation
      h2 = "#{pluralize(@loan.errors.count, "error")} prohibited this loan from being saved:"
      ul
        - @loan.errors.full_messages.each do |message|
          li = message

  / .field
  /   = f.label :title
  /   = f.text_field :title
  / .field
  /   = f.label :author
  /   = f.text_field :author
  / .field
  /   = f.label :date
  /   = f.date_select :date
  / .field
  /   = f.label :loan
  /   = f.text_field :loan
  / .actions 

  - book =  Book.find(params["book_id"])
  - author = Author.find(book.author_id)

  h3 = book.title
  h4 = author.name

  .actions = f.submit 'Save'

app/views/loans/_loan_list.html.slim
table
  thead
    tr
      th Title
      th Author
      th Date
      th Loan
      th Status

  tbody
    - Loan.all.each do |loan|
      tr
        td
        td
        td = loan.date
        td = loan.loan
        td = loan.status

app/views/loans/edit.html.slim
h1 Editing loan

== render 'form'

= link_to 'Show', @loan
'|
= link_to 'Back', loans_path

app/views/loans/index.html.slim
h1 Listing loans

table
  thead
    tr
      th Title
      th Author
      th Date
      th Loan
      th Status
      th
      th
      th

  tbody
    - @loans.each do |loan|
      tr
        td
        td
        td = loan.date
        td = loan.loan
        td = loan.status
        td = link_to 'Show', loan
        td = link_to 'Edit', edit_loan_path(loan)
        td = link_to 'Destroy', loan, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Loan', new_book_loan_path

app/views/loans/new.html.slim
h1 New loan

== render 'form'

= link_to 'Back', books_path

app/views/loans/show.html.slim
p#notice = notice

p
  strong Date:
  = @loan.date
p
  strong Loan:
  = @loan.loan
p
  strong Status:
  = @loan.status

= link_to 'Edit', edit_loan_path(@loan)
'|
= link_to 'Back', loans_path